import Head from "next/head";
import { useState } from "react";
import {
  ComposableMap,
  Geographies,
  Geography,
  ZoomableGroup,
} from "react-simple-maps";
import { Tooltip } from "react-tooltip";

export default function Home() {
  const [content, setContent] = useState("");
  // const geoUrl =
  //   "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";

  return (
    <>
      <Head>
        <title>Map-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="app">
          <h1>Mappy Map</h1>
          <Tooltip id="my-tooltip" />
          <div className="map">
            <ComposableMap data-tip="">
              <ZoomableGroup zoom={1}>
                <Geographies
                  geography={
                    "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
                  }
                >
                  {({ geographies }) =>
                    geographies.map((geo) => (
                      <Geography
                        key={geo.rsmKey}
                        geography={geo}
                        data-tooltip-id="my-tooltip"
                        data-tooltip-content={content}
                        onMouseEnter={() => {
                          setContent(`${geo.properties.name}`);
                        }}
                        onMouseLeave={() => {
                          setContent("");
                        }}
                        style={{
                          default: {
                            fill: "#D6D6DA",
                            outline: "none",
                          },
                          hover: {
                            fill: "#F53",
                            outline: "none",
                          },
                          pressed: {
                            fill: "#E42",
                            outline: "none",
                          },
                        }}
                      />
                    ))
                  }
                </Geographies>
              </ZoomableGroup>
            </ComposableMap>
          </div>
        </div>
      </main>
    </>
  );
}
