import Head from "next/head";
import { useState } from "react";
import {
  ComposableMap,
  Geographies,
  Geography,
  ZoomableGroup,
} from "react-simple-maps";
import { Tooltip } from "react-tooltip";
import Modal from "../../components/Modal";
import { StyledButton, StyledButtonContainer } from "../../components/Button";

export default function Home() {
  const [content, setContent] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isVisited, setIsVisited] = useState(false);

  function openModal() {
    setIsModalOpen(!isModalOpen);
  }

  function handleVisit(content) {
    setIsVisited(!isVisited);

    // projects.map((project) =>
    //   project.id === id
    //     ? { ...project, favorite: !project.favorite }
    //     : project
    // )

    openModal();
  }

  return (
    <>
      <Head>
        <title>Map-test</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <div className="app">
          <h1>Mappy Map</h1>
          <p>zoom in || move around || hover</p>

          <p>more interactivity is coming soon...</p>

          <Tooltip id="my-tooltip" />
          <div className="map">
            <ComposableMap data-tip="">
              <ZoomableGroup zoom={1}>
                <Geographies
                  geography={
                    "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
                  }
                >
                  {({ geographies }) =>
                    geographies.map((geo) => (
                      <Geography
                        key={geo.rsmKey}
                        geography={geo}
                        data-tooltip-id="my-tooltip"
                        data-tooltip-content={content}
                        onMouseEnter={() => {
                          setContent(`${geo.properties.name}`);
                        }}
                        style={{
                          default: {
                            fill: isVisited ? "#9BEC00" : "#D6D6DA",
                            outline: "none",
                          },
                          hover: {
                            fill: "#FF9A00",
                            outline: "none",
                          },
                        }}
                        onClick={() => {
                          openModal({ content });
                        }}
                      />
                    ))
                  }
                </Geographies>
              </ZoomableGroup>
            </ComposableMap>

            {isModalOpen && (
              <Modal onCancel={openModal} content={content}>
                <p>
                  Do you want to add {content} to your list of visited
                  destinations?
                </p>
                <StyledButtonContainer>
                  <StyledButton
                    type="button"
                    onClick={() => handleVisit(content)}
                  >
                    yes
                  </StyledButton>
                  <StyledButton type="button" onClick={openModal}>
                    no
                  </StyledButton>
                </StyledButtonContainer>
              </Modal>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
